### ISSUE TITLE
Change `represent_cc_identity` behaviour for `spa.State`

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo-spa#269]
I know I probably had a pretty heavy say in the original decision to have `represent_cc_identity` True by default, but playing around more with the `nengo_spa` code (spurred by [this ](https://forum.nengo.ai/t/nengo-summer-school-2020-basic-integrator-memory-vs-state-memory/1400)discussion), I think we should modify how the default behaviour of `represent_cc_identity`. 

From my experimentations, `represent_cc_identity` really only affects the `spa.State` network only when `subdimensions == 1`. In any other case, the multi-dimensional sub-dimensions are able to correctly represent the identity vector, so `represent_cc_identity` isn't really needed. Additionally, when `subdimensions > 1`, having `represent_cc_identity` the way it is now can cause the stored memory vector to have a magnitude that far exceeds the expected 1 - 1.5. This is because the first dimension of the vector can theoretically store a value of 1 regardless of what the other vector dimensions saturate at.

So, my proposal is to change the behaviour to do either of the three options below:

1. Leave `represent_cc_identity` the way it is, but only use the `IdentityEnsembleArray` only when `subdimensions == 1`. Also document this behaviour in the comment field for `represent_cc_identity`.

2. Remove `represent_cc_identity`, and use `IdentityEnsembleArray` when `subdimensions == 1`. The accuracy loss due to the loss of representation resolution in the first dimension shouldn't be that impactful if the number of dimensions for `spa.State` is large enough. But... this introduces some black magic into the code which may confuse users, so documentation is required.

3. Change the `represent_cc_identity` to `represent_identity` or something like that, and pass the `spa.State` module an initializer for the `EnsembleArray`. This will allow more flexibility in `spa.State` and allow it to be used with other vector representations that may have other special case vectors, similar to how the HRR has the special case identity vector.

**Comment by tcstewar** [comment]
Interesting....  I hadn't thought of that interaction between `represent_cc_identity` and the `subdimensions`....  hmm...

Just so I understand, for option 1 are you proposing that for `subdimensions>1` the setting of `represent_cc_identity` would be ignored?  So it would still default to True, but it would only actually have an effect if `subdimensions==1`?  If so, I think that's my perferred option.  It'd require some careful documentation, but no more so than the current approach.  And it would simplify some of the things that come up for me both when teaching `nengo_spa` (questions come up about the complexity of the internals of a spa.State) and when publishing papers with it (I basically always do `represent_cc_identity=False` when publishing because it's simpler to explain).

For option 2, is that the same as option 1 but just removing the parameter so it can't be controlled?  

I do like the idea behind option 3, but I'm worried about adding features to the API that don't have an explicit use case yet, so I'd hold off on something like that until we have a system with another special case vector we might want to use.

**Comment by arvoelke** [comment]
Option 4? Apply a [random orthogonal matrix](https://arvoelke.github.io/nengolib-docs/nengolib.stats.random_orthogonal.html) to the encoding so that the identity vector looks like any other Semantic Pointer. Then there would be no need for this flag. But the challenge would be doing this in a way that is "invisible" to the user. I think it shouldn't be too bad as the inverse of an orthogonal matrix is its transpose, and you could hide the two transformations from the user inside the module?

**Comment by tcstewar** [comment]
Just to add other options, at some point it might also make sense to try an option 5: default subdimensions=dimensions, so there isn't any of this splitting at all, and give an interestingly configured `solver` that would work okay with that many neurons.  I don't know how big an Ensemble is feasible now, but that'd bypass this problem nicely....

That said, I think for the purposes of this PR, it'd be good to just go with a pretty simple option (like Option 1), and look into these other possibilities in the future.

**Comment by xchoo** [comment]
> Just so I understand, for option 1 are you proposing that for subdimensions>1 the setting of represent_cc_identity would be ignored? So it would still default to True, but it would only actually have an effect if subdimensions==1?

Yes. This is correct. Technically, when `subdimensions > 1`, `represent_cc_identity` is already satisfied, because multi-(sub)dimensional ensembles would be able to represent the circular convolution identity vector. The only case where it can't is when `subdimensions == 1` (because of the `1 / sqrt(D)` expected value for HRR vectors)

**Comment by xchoo** [comment]
Oop. No. Scratch that. I just ran a quick experiment. Turns out `represent_cc_identity` is still fairly important. Especially when D gets big. 

See:
```
import matplotlib.pyplot as plt

import nengo
import nengo_spa as spa


def input_func(t):
    return "1"

with spa.Network() as model:
    probes = []

    for dim in [1, 16, 64, 512]:
        spa_input = spa.Transcode(input_func, output_vocab=dim)
        spa_state = spa.State(dim, subdimensions=min(dim, 16), represent_cc_identity=False)
        nengo.Connection(spa_input.output, spa_state.input)
        probes.append(nengo.Probe(spa_state.output, synapse=0.05))

with nengo.Simulator(model) as sim:
    sim.run(1)

print(model.vocabs[1]["I"].v)

plt.figure()
plt.plot(sim.trange(), sim.data[probes[0]][:, 0], label="1D")
plt.plot(sim.trange(), sim.data[probes[1]][:, 0], label="16D")
plt.plot(sim.trange(), sim.data[probes[2]][:, 0], label="64D")
plt.plot(sim.trange(), sim.data[probes[3]][:, 0], label="512D")
plt.legend()
plt.title("Value of D[0]")
plt.show()
```

Which gives this plot:
![image](https://user-images.githubusercontent.com/1971583/95161681-d0295280-0771-11eb-8c72-3a1d0f54b121.png)


Although, using @tcstewar suggestion of fixing `subdimensions = dimensions` would avoid this whole issue altogether. These are the build times for various ensemble sizes using `n_neurons = 50 (the default) * D`:
```
16D NN=800 Build time: 0.1032s
64D NN=3200 Build time: 0.1027s
128D NN=6400 Build time: 0.2033s
256D NN=12800 Build time: 0.8060s
512D NN=25600 Build time: 2.4303s
1024D NN=51200 Build time: 9.8104s
```
And this is being run on an 8 year old processor. It's a desktop processor though... so * 3 - 5 for modern power-saving laptop processors?

Anyho.. closing the issue now.

**Comment by arvoelke** [comment]
> we should modify the API to support other special case vectors though

With option 4 there aren't any special case vectors. So I think your original concerns go away and all you need is the normal `EnsembleArray`. Another cool part about it is the feedback connection is still the same because `M^T M = M M^T = I`. So I think it's worth looking at when this comes up again.

**Comment by jgosmann** [comment]
A few notes:

* I don't think `subdimensions = dimensions` is a scalable default (without some very clever solver). Not only build time increases, but also memory consumption (I am not able to build a the 512 dimensional ensemble on my 2014 MacBook which has only 16GB RAM). This increase is at least quadratic (maybe cubic?).
* The random orthogonal matrix approach is interesting. I wonder whether we discussed that previously or just did not think of it at that time.
* I could see adding an argument/config option for the specific network that `spa.State` uses internally. That would allow to swap it out to handle other specific cases if they come up and also use a network providing the random orthogonal matrix approach. Not 100% sure how the API for that would look like: on the one hand I'd like to keep a simple option to turn `represent_cc_identity` off (without the fuzz of providing `EnsembleArray` explicitly to do that), but on the other hand I would like to avoid duplication in the arguments (at least long term, at first it would only be deprecated and not be removed until the next major release).

**Comment by jgosmann** [comment]
For the sake of completeness link to previous discussion: https://github.com/nengo/nengo-spa/pull/4#issuecomment-299979420

**Comment by xchoo** [comment]
> I don't think subdimensions = dimensions is a scalable default (without some very clever solver). Not only build time increases, but also memory consumption (I am not able to build a the 512 dimensional ensemble on my 2014 MacBook which has only 16GB RAM). This increase is at least quadratic (maybe cubic?).

See above:
Ensemble build times (on my 9 y/o Intel Core i7-3770 w/ 16 GB ram) - 
```
16D NN=800 Build time: 0.1032s
64D NN=3200 Build time: 0.1027s
128D NN=6400 Build time: 0.2033s
256D NN=12800 Build time: 0.8060s
512D NN=25600 Build time: 2.4303s
1024D NN=51200 Build time: 9.8104s
```

I was surprised I could build a 512D ensemble on my machine.. I recall not being able to do it before (at least in < 1 min). Here's the code I used to test the build times. Perhaps I was overlooking something?

```
import nengo
import time


nn = 50

for dim in [16, 64, 128, 256, 512, 1024]:
    with nengo.Network() as model:
        ens = nengo.Ensemble(n_neurons=nn * dim, dimensions=dim)

    start_time = time.time()
    sim = nengo.Simulator(model)
    print("%iD" % dim, "NN=%i" % (nn * dim),
          "Build time: %0.4fs" % (time.time() - start_time))
```

**Comment by tcstewar** [comment]
> Perhaps I was overlooking something?

Hmm, looks like there's no decoder there....   it might be a lot longer with a `nengo.Connection(ens, ens)` as well....

I've had success building large ensembles like that, but I've had to switch to one of the more fun solvers.

**Comment by xchoo** [comment]
Ah. I was wondering about that. With the default solvers, I get these results (I forced the decoder solver by adding a probe to the ensemble):
```
Build finished in 0:00:01.
4D NN=200 Build time: 0.1025s
Build finished in 0:00:01.
8D NN=400 Build time: 0.2028s
Build finished in 0:00:01.
16D NN=800 Build time: 0.3036s
Build finished in 0:00:01.
32D NN=1600 Build time: 0.8142s
Build finished in 0:00:03.
64D NN=3200 Build time: 3.0503s
Build finished in 0:00:16.
128D NN=6400 Build time: 15.2367s
Build finished in 0:02:30.
256D NN=12800 Build time: 149.3669s
```

That looks more like what I expected.

**Comment by tcstewar** [comment]
> That looks more like what I expected.

Ah, yup.  Good to know that subdimensions is still kinda needed.  I've always felt rather uncomfortable about it, but I think it's still necessary.  I've had some good luck with `nengo.solvers.LstsqL2(solver=lss.LSMRScipy())` for these larger datasets, but that's with a pretty good scipy and numpy installed.

I do like @arvoelke's suggestion of doing a random rotation, so each subensemble is representing a randomly rotated subspace rather than axis-aligned subspaces....  And if that's taken care of by the `Connection`s from the `input` to the ensembles and from the ensembles to the `output` then it's pretty invisible to the outside.
